### ISSUE TITLE
Can esx-boot boot Linux?

### ISSUE THREAD

**Issue by thatsysadmin** [vmware/esx-boot#10]
Curiosity's killing me. I know esx-boot is only intended for booting ESXi, but I'm curious as to what would it take to get esx-boot to boot other kernels?

**Comment by TimothyPMann** [comment]
esx-boot might successfully boot a kernel that conforms to the old Multiboot standard, but that support is there only because older versions of ESX used Multiboot. esx-boot is not tested with any other OS.

**Comment by thatsysadmin** [comment]
Ok. Thanks!
