### ISSUE TITLE
ESXi 7.0u3 historical security problem not solved with broken wget for https

### ISSUE THREAD

**Issue by Neustradamus** [vmware/esx-boot#12]
### Describe the bug

Dear @vmware, @vmware-labs teams,

This security problem is not new (several years), can you solve the broken wget for https requests in ESXi 7.0u3 and more?

For example:
```
wget https://cdimage.debian.org/debian-cd/current/amd64/iso-cd/debian-XX.X.X-amd64-netinst.iso
Connecting to cdimage.debian.org (XXX.XX.XX.XXX:443)
wget: error getting response: Cannot assign requested address
```

Security of users is the most important, it is important to fix it!

Thanks in advance.

### Reproduction steps

1. Enable SSH on host
2. Connect to SSH on host
3. Enable httpClient: esxcli network firewall ruleset set --enabled=true --ruleset-id=httpClient
4. Type for example: wget https://cdimage.debian.org/debian-cd/current/amd64/iso-cd/debian-XX.X.X-amd64-netinst.iso
5. You see the result, it does not work.
...

### Expected behavior

No error: `wget: error getting response: Cannot assign requested address`

**Comment by TimothyPMann** [comment]
This issue has absolutely nothing to do with esx-boot. Please report it through a proper channel.

Also, it is not a security issue.

**Comment by TimothyPMann** [comment]
Please file an SR. If you don't have entitlement to file an SR, please ask a question in the Communities forums at https://communities.vmware.com/. Do not pick a random VMware open source project on GitHub and expect the maintainer to support you on issues in completely different areas of VMware software.
