### ISSUE TITLE
what nic river does exsi support?

### ISSUE THREAD

**Issue by tscswcn** [vmware/esx-boot#5]
what nic river does exsi support for linux? 
e1000 ? 

or can exsi host support cirros img with e1000 nic driver or other nic drivers?

**Comment by TimothyPMann** [comment]
This is not an esx-boot issue, but I'll try to answer the question.

An ESXi VM can have several types of virtual NIC. See https://kb.vmware.com/s/article/1001805.

I don't know what NIC drivers are included in Cirros.
