### ISSUE TITLE
ld: elf2efi cannot handle a PLT

### ISSUE THREAD

**Issue by khemir33** [vmware/esx-boot#8]
Hi, 

I am getting this error when trying compile:

```
...
[uefi64 CC] iso9660/fsw_iso9660.o
[uefi64 LD] iso9660/iso9660_em64t.elf
ld: elf2efi cannot handle a PLT
make[3]: *** [rules.mk:52: ../../build/uefi64/iso9660/iso9660_em64t.elf] Error 1
make[2]: *** [Makefile:28: iso9660] Error 2
make[1]: *** [Makefile.main:37: uefi] Error 2
make: *** [Makefile:37: uefi64] Error 2
server#
```
CentOS 8
gcc --version
gcc (GCC) 8.3.1 20191121 (Red Hat 8.3.1-5)
Python 2.7.17

Please you help to this error:

ld: elf2efi cannot handle a PLT

**Comment by TimothyPMann** [comment]
Odd, all the versions of gcc I've used don't generate a PLT when compiling with the flags that we use.  Can you do "make clean; make VERBOSE=1" to see exactly what flags are set?

**Comment by khemir33** [comment]
Hi Timothy, 

```
...
[uefi64 CC] iso9660/fsw_iso9660.o
gcc -m64 -mno-red-zone -msoft-float -DNO_MSABI_VA_FUNCS -fshort-wchar -fno-dwarf2-cfi-asm -fpie --sysroot='/' -Donly_em64t -Donly_x86 -DVMWARE_EDK2_CHANGES -ffreestanding -fno-exceptions -Os -fstrength-reduce -ffast-math -fomit-frame-pointer -finline-limit=2000 -freg-struct-return -fno-strict-aliasing -falign-functions=0 -falign-jumps=0 -falign-labels=0 -falign-loops=0 -fwrapv -fvisibility=hidden -fstack-protector -fstack-protector-all -mstack-protector-guard=global -W -Wall -Werror -std=c99 -Wwrite-strings -Wstrict-prototypes -Wpointer-arith -Wdeclaration-after-statement -Wvla -Woverlength-strings -Wredundant-decls -Wformat -Wno-implicit-fallthrough -g -DFSTYPE=iso9660 -DFSW_DEBUG_LEVEL=0 -DHOST_EFI -I../../libc/include -I../../include -I../../include/x86 -I../../libmd5 -I../../uefi -I../../uefi/edk2/MdePkg/Include -I../../uefi/edk2/MdePkg/Include/X64 -I../../uefi/edk2/MdePkg/Include/Protocol -I../../uefi/edk2/EmbeddedPkg/Include -c -o ../../build/uefi64/iso9660/fsw_iso9660.o fsw_iso9660.c
[uefi64 LD] iso9660/iso9660_em64t.elf
ld -m elf_x86_64 --defsym _start=efi_main -nostdlib -q -T ../../uefi/uefi.lds  -o ../../build/uefi64/iso9660/iso9660_em64t.elf ../../build/uefi64/iso9660/fsw_efi.o ../../build/uefi64/iso9660/fsw_efi_lib.o ../../build/uefi64/iso9660/fsw_core.o ../../build/uefi64/iso9660/fsw_lib.o ../../build/uefi64/iso9660/fsw_iso9660.o -\( ../../build/uefi64/lib/uefiem64t/libuefiem64t.a ../../build/uefi64/lib/fat/libfat.a ../../build/uefi64/lib/c/libc.a ../../build/uefi64/lib/crc/libcrc.a ../../build/uefi64/lib/md5/libmd5.a ../../build/uefi64/lib/uart/libuart.a ../../build/uefi64/lib/z/libz.a /usr/lib/gcc/x86_64-redhat-linux/8/libgcc.a ../../build/uefi64/lib/boot/libboot.a -\)
ld: elf2efi cannot handle a PLT
make[3]: *** [rules.mk:52: ../../build/uefi64/iso9660/iso9660_em64t.elf] Error 1
make[2]: *** [Makefile:28: iso9660] Error 2
make[1]: *** [Makefile.main:37: uefi] Error 2
make: *** [Makefile:37: uefi64] Error 2
server#
```
Thanks.

**Comment by TimothyPMann** [comment]
OK, it's not the CC or LD flags. There must be something different about "gcc (GCC) 8.3.1 20191121 (Red Hat 8.3.1-5)".

I've compiled successfully with:
gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04) 
gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04)  - with a workaround for an unrelated Ubuntu issue
and some older versions as well.

Try the following to see more about what ended up in the PLT. This will just print the PLT in hex, though. I am forgetting exactly what objdump flags or other techniques I used last time I saw a nonempty PLT get generated. That was quite a white ago.

elf2efi has some flags, but I see no one remembered to add them to the usage message.  Using -v -v may be useful, though it may print a lot of noise too.

**Comment by khemir33** [comment]
Hi Timothy
That files not found, i guest build don't success

```
$ objdump -h build/uefi64/iso9660/iso9660_em64t.elf
objdump: 'build/uefi64/iso9660/iso9660_em64t.elf': No such file
$ objdump -j .plt -s build/uefi64/iso9660/iso9660_em64t.elf
objdump: 'build/uefi64/iso9660/iso9660_em64t.elf': No such file
objdump: section '.plt' mentioned in a -j option, but not found in any input file
```
Thanks

**Comment by TimothyPMann** [comment]
That file is the input to the elf2efi run that you got an error in, so it must have existed when you got the error.  I don't think "make" should have deleted the .elf file after elf2efi failed. Maybe you tried this after a "make clean"? If so, try doing "make" to get the .elf file generated again.

**Comment by khemir33** [comment]
Hello Timothy
After you help i find the issue.
1.-Its very important install all dependency on toolchain.mk
2.-Use python2.7 and create soft link to python
After that compile run .. :)

Thanks for amazing tool.

**Comment by TimothyPMann** [comment]
OK, good to hear that. I still wonder exactly how you got the PLT error, but I'll close this.
